apiVersion: v1
kind: Namespace
metadata:
  name: datahack-ns
  labels:
    name: datahack
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: datahack-ns
type: Opaque
stringData:
  POSTGRES_PASSWORD: "testpass"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: datahack-ns
data:
  POSTGRES_USER: "testuser"
  POSTGRES_DB: "datahack"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: python-config
  namespace: datahack-ns
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  VERSION: "0.0.0-SYM"


