apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: datahack-ns
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres-service
  replicas: 1
  template:
    metadata:
      namespace: datahack-ns
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14
        resources: {}
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        envFrom:
        - secretRef:
            name: postgres-secret
        - configMapRef:
            name: postgres-config
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
      namespace: datahack-ns
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: datahack-ns
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
