services:
  db-compose:
    image: postgres:14
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb # Recommended in dockerhub
    expose:
      - 5432 # This DOES NOT expose the port to host machine
    environment:
      POSTGRES_PASSWORD: testpass
      POSTGRES_USER: testuser
      POSTGRES_DB: datahack
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "datahack"]
      interval: 10s
      timeout: 5s
      retries: 5 
    volumes:
      - db_data_compose:/var/lib/postgresql/data
  
  api-compose:
    build:
      context: ../1_docker
      dockerfile: Dockerfile
    # Uncomment next line to test image pull from dockerhub (it is public) and comment build section
    # image: sergioym/api-docker:2.0.0
    restart: always
    depends_on:
      db-compose:
        condition: service_healthy
    ports:
      - 8081:5000 # This DOES expose the port to host machine
    environment:
      DB_USER: testuser
      DB_PASSWORD: testpass
      DB_HOST: db-compose
      DB_PORT: 5432
      DB_NAME: datahack
      VERSION: 0.0.0-SYM

volumes:
  db_data_compose:
